//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParserIO.DAO
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformationSet", Namespace="http://schemas.datacontract.org/2004/07/ParserIO.DAO")]
    public partial class InformationSet : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ACLField;
        
        private string ADDITIONALIDField;
        
        private string AdditionalInformationField;
        
        private string BESTBEFOREField;
        
        private string CIPField;
        
        private string CONTENTField;
        
        private string COUNTField;
        
        private string CompanyField;
        
        private bool ContainsOrMayContainIdField;
        
        private string EANField;
        
        private string ExpiryField;
        
        private string FamilyField;
        
        private string GTINField;
        
        private string LICField;
        
        private string LPPField;
        
        private string LotField;
        
        private string NaS7Field;
        
        private string NaSIdParamNameField;
        
        private string NormalizedBESTBEFOREField;
        
        private string NormalizedExpiryField;
        
        private string NormalizedPRODDATEField;
        
        private string PCNField;
        
        private string PRODDATEField;
        
        private string ProductField;
        
        private string QuantityField;
        
        private string ReferenceField;
        
        private string SSCCField;
        
        private string SerialField;
        
        private string SubTypeField;
        
        private string SymbologyIDField;
        
        private string TypeField;
        
        private string UDIField;
        
        private string UPNField;
        
        private string UoMField;
        
        private string VARCOUNTField;
        
        private string VARIANTField;
        
        private int executeResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACL
        {
            get
            {
                return this.ACLField;
            }
            set
            {
                this.ACLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADDITIONALID
        {
            get
            {
                return this.ADDITIONALIDField;
            }
            set
            {
                this.ADDITIONALIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalInformation
        {
            get
            {
                return this.AdditionalInformationField;
            }
            set
            {
                this.AdditionalInformationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BESTBEFORE
        {
            get
            {
                return this.BESTBEFOREField;
            }
            set
            {
                this.BESTBEFOREField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CIP
        {
            get
            {
                return this.CIPField;
            }
            set
            {
                this.CIPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CONTENT
        {
            get
            {
                return this.CONTENTField;
            }
            set
            {
                this.CONTENTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COUNT
        {
            get
            {
                return this.COUNTField;
            }
            set
            {
                this.COUNTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ContainsOrMayContainId
        {
            get
            {
                return this.ContainsOrMayContainIdField;
            }
            set
            {
                this.ContainsOrMayContainIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EAN
        {
            get
            {
                return this.EANField;
            }
            set
            {
                this.EANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Expiry
        {
            get
            {
                return this.ExpiryField;
            }
            set
            {
                this.ExpiryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Family
        {
            get
            {
                return this.FamilyField;
            }
            set
            {
                this.FamilyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GTIN
        {
            get
            {
                return this.GTINField;
            }
            set
            {
                this.GTINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LIC
        {
            get
            {
                return this.LICField;
            }
            set
            {
                this.LICField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LPP
        {
            get
            {
                return this.LPPField;
            }
            set
            {
                this.LPPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lot
        {
            get
            {
                return this.LotField;
            }
            set
            {
                this.LotField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NaS7
        {
            get
            {
                return this.NaS7Field;
            }
            set
            {
                this.NaS7Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NaSIdParamName
        {
            get
            {
                return this.NaSIdParamNameField;
            }
            set
            {
                this.NaSIdParamNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NormalizedBESTBEFORE
        {
            get
            {
                return this.NormalizedBESTBEFOREField;
            }
            set
            {
                this.NormalizedBESTBEFOREField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NormalizedExpiry
        {
            get
            {
                return this.NormalizedExpiryField;
            }
            set
            {
                this.NormalizedExpiryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NormalizedPRODDATE
        {
            get
            {
                return this.NormalizedPRODDATEField;
            }
            set
            {
                this.NormalizedPRODDATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PCN
        {
            get
            {
                return this.PCNField;
            }
            set
            {
                this.PCNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRODDATE
        {
            get
            {
                return this.PRODDATEField;
            }
            set
            {
                this.PRODDATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reference
        {
            get
            {
                return this.ReferenceField;
            }
            set
            {
                this.ReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSCC
        {
            get
            {
                return this.SSCCField;
            }
            set
            {
                this.SSCCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serial
        {
            get
            {
                return this.SerialField;
            }
            set
            {
                this.SerialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubType
        {
            get
            {
                return this.SubTypeField;
            }
            set
            {
                this.SubTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SymbologyID
        {
            get
            {
                return this.SymbologyIDField;
            }
            set
            {
                this.SymbologyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UDI
        {
            get
            {
                return this.UDIField;
            }
            set
            {
                this.UDIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPN
        {
            get
            {
                return this.UPNField;
            }
            set
            {
                this.UPNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UoM
        {
            get
            {
                return this.UoMField;
            }
            set
            {
                this.UoMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VARCOUNT
        {
            get
            {
                return this.VARCOUNTField;
            }
            set
            {
                this.VARCOUNTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VARIANT
        {
            get
            {
                return this.VARIANTField;
            }
            set
            {
                this.VARIANTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int executeResult
        {
            get
            {
                return this.executeResultField;
            }
            set
            {
                this.executeResultField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IParserIO")]
public interface IParserIO
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParserIO/GetFullInformationSet", ReplyAction="http://tempuri.org/IParserIO/GetFullInformationSetResponse")]
    ParserIO.DAO.InformationSet GetFullInformationSet(string code);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParserIO/GetFullInformationSet", ReplyAction="http://tempuri.org/IParserIO/GetFullInformationSetResponse")]
    System.Threading.Tasks.Task<ParserIO.DAO.InformationSet> GetFullInformationSetAsync(string code);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IParserIOChannel : IParserIO, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ParserIOClient : System.ServiceModel.ClientBase<IParserIO>, IParserIO
{
    
    public ParserIOClient()
    {
    }
    
    public ParserIOClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ParserIOClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ParserIOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ParserIOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ParserIO.DAO.InformationSet GetFullInformationSet(string code)
    {
        return base.Channel.GetFullInformationSet(code);
    }
    
    public System.Threading.Tasks.Task<ParserIO.DAO.InformationSet> GetFullInformationSetAsync(string code)
    {
        return base.Channel.GetFullInformationSetAsync(code);
    }
}
